### PR TITLE
Upgrade for webpack 4

### PR DESCRIPTION
**Pull request by lemonCMS**
This pull request uses the new .hooks api.

I must say this.hooks api needs a extra parameter options. and within options the name attribute must be present. Right now i pass the plugin.options object, but i truly do not know if this is correct or overkill.

Does anyone have a idea?

### CODE REVIEW

**Comment by catamphetamine** [comment]
@lemonCMS Oh, indeed, time has come to upgrade this one.
I'll make the changes based on your code and release a new version today.
Thanks for the PR, I'm closing it.

**Comment by catamphetamine** [comment]
Closed in https://github.com/catamphetamine/webpack-isomorphic-tools/issues/156

**Comment by catamphetamine** [comment]
@lemonCMS 
Try version `3.0.6` and see if it works.
I don't have a project for testing the new version.

**Comment by lemonCMS** [comment]
Thx, it seems to be working!

**Pull request closed without merging**
